export const types = {
  MONSTER_SELECTED: "MONSTER_SELECTED",
  ADD_MONSTER_TO_COMBATANTS: "ADD_MONSTER_TO_COMBATANTS",
  FILTER_MONSTER_LIBRARY: "FILTER_MONSTER_LIBRARY",
  CHANGE_MONSTER_HP: "CHANGE_MONSTER_HP",
  REMOVE_COMBATANT: "REMOVE_COMBATANT",
  D20_ROLLED: "D20_ROLLED",
  DELETE_ROLL: "DELETE_ROLL",
  SIDED_DICE_ROLLED: "SIDED_DICE_ROLLED",
  CLEAR_COMBATANTS: "CLEAR_COMBATANTS",
  CLEAR_ROLLS: "CLEAR_ROLLS",
  ROLL_INITIATIVES: "ROLL_INITIATIVES",
  FETCH_MONSTERS: "FETCH_MONSTERS"
};

export default types;
