export const types = {
  MONSTER_SELECTED: "MONSTER_SELECTED",
  ADD_MONSTER_TO_COMBATANTS: "ADD_MONSTER_TO_COMBATANTS",
  FILTER_MONSTER_LIBRARY: "FILTER_MONSTER_LIBRARY",
  CHANGE_MONSTER_HP: "CHANGE_MONSTER_HP"
};

export default types;
